spring.application.name: demo

# Enable HTTP/2 for the Tomcat servlet container
server.http2.enabled: true

server:
  servlet:
    context-parameters:
      enableLoggingRequestDetails: true
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.a2aproject.sdk: DEBUG

