spring.application.name: demo

server:
  servlet:
    context-parameters:
      enableLoggingRequestDetails: true
  port: 8080

spring:
  grpc:
    server:
      port: 9090
      inprocess:
        name: a2a-grpc-server

logging:
  level:
    org.springframework.web: DEBUG
    org.a2aproject.sdk: DEBUG

